"""finding publish tracking (confluence/jira)

Revision ID: 1879578a325c
Revises: 97dbf9f1c9a3
Create Date: 2026-09-15 16:37:59.587115
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '1879578a325c'
down_revision: Union[str, None] = '97dbf9f1c9a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finding', sa.Column('confluence_page_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('finding', sa.Column('jira_issue_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('finding', 'jira_issue_key')
    op.drop_column('finding', 'confluence_page_id')
    # ### end Alembic commands ###
