"""asset notes

Revision ID: 3be4d52c842f
Revises: 1879578a325c
Create Date: 2026-09-15 21:36:05.397776
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '3be4d52c842f'
down_revision: Union[str, None] = '1879578a325c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset', 'notes')
    # ### end Alembic commands ###
