"""finding.asset_id link

Revision ID: 42944168d476
Revises: 8c84dd78fb07
Create Date: 2026-09-15 15:52:23.719467
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '42944168d476'
down_revision: Union[str, None] = '8c84dd78fb07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finding', sa.Column('asset_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_finding_asset_id'), 'finding', ['asset_id'], unique=False)
    op.create_foreign_key(None, 'finding', 'asset', ['asset_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'finding', type_='foreignkey')
    op.drop_index(op.f('ix_finding_asset_id'), table_name='finding')
    op.drop_column('finding', 'asset_id')
    # ### end Alembic commands ###
