"""finding taxonomy fields + evidence.finding_id + draft status

Revision ID: 8c84dd78fb07
Revises: 34c0570a698b
Create Date: 2026-09-15 15:19:07.194124
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '8c84dd78fb07'
down_revision: Union[str, None] = '34c0570a698b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidence', sa.Column('finding_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_evidence_finding_id'), 'evidence', ['finding_id'], unique=False)
    op.create_foreign_key(None, 'evidence', 'finding', ['finding_id'], ['id'])
    op.add_column('finding', sa.Column('business_impact', sa.Text(), nullable=True))
    op.add_column('finding', sa.Column('reproduction_steps', sa.Text(), nullable=True))
    op.add_column('finding', sa.Column('raw_notes', sa.Text(), nullable=True))
    op.add_column('finding', sa.Column('cve', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('finding', sa.Column('references', sa.JSON(), nullable=True))
    op.add_column('findingtemplate', sa.Column('business_impact', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('findingtemplate', 'business_impact')
    op.drop_column('finding', 'references')
    op.drop_column('finding', 'cve')
    op.drop_column('finding', 'raw_notes')
    op.drop_column('finding', 'reproduction_steps')
    op.drop_column('finding', 'business_impact')
    op.drop_constraint(None, 'evidence', type_='foreignkey')
    op.drop_index(op.f('ix_evidence_finding_id'), table_name='evidence')
    op.drop_column('evidence', 'finding_id')
    # ### end Alembic commands ###
