"""service.description

Revision ID: 97dbf9f1c9a3
Revises: 42944168d476
Create Date: 2026-09-15 16:07:08.388213
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '97dbf9f1c9a3'
down_revision: Union[str, None] = '42944168d476'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'description')
    # ### end Alembic commands ###
